import time

files = [
    'species.cpp',
    'creature.cpp',
    'grid.cpp',
    'world.cpp',
    'controller.cpp',
    'exception.cpp'
]

out = open('simulation.cpp', 'w')

head = [
    '// Generated by p3 builder v0.1',
    '// Author: tc-imba',
    '// Date: ' + time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())),
    '',
    '#include <iostream>',
    '#include <sstream>',
    '#include <fstream>',
    '#include "simulation.h"',
    '',
    'namespace p3',
    '{',
    ''
]

out.write('\n'.join(head))

for filename in files:
    f = open(filename, 'r')
    flag = 1
    for line in f:
        if flag:
            if line[0] != '\n' and line[0] != '/' and line[0] != '#' and line[0] != ' ':
                flag = 0
                out.write('\n\n\n    // ' + filename + '\n')
        else:
            out.write('    ')
            out.write(line)

out.write('\n\n}\n\n')